weights: '/content/matrice-updated/src/weights/yolov9-c.pt'
cfg: '/content/Jat_seg.yaml'
data: '/content/DeepFashion2-1/data.yaml'
hyp: '/content/matrice-updated/src/yolov9/data/hyps/hyp.scratch-high.yaml'
epochs: 100
batch_size: 8
imgsz: 640
workers: 8
device: 0
rect: store_true
name: 'Detection_Instance'
no_overlap: true
close_mosaic: 10
resume: false
nosave: false
noval: false
noautoanchor: false
noplots: false
evolve: null
bucket: ''
cache: null
image_weights: false
multi_scale: false
single_cls: false
optimizer: 'SGD'
sync_bn: false
project: 'runs/train-seg'
exist_ok: false
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 100
freeze: [0]
save_period: -1
seed: 0
local_rank: -1
mask_ratio: 4
